<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload-Photo</name>
   <tag></tag>
   <elementGuidId>63c887fc-47e7-4b51-994b-2f9bdbce0776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uploadPicture&#xd;
']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadPicture']&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadPicture&#xd;
</value>
      <webElementGuid>e82807d7-088d-4500-be12-5d671b70dbbe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
